name: Publish Container Image

on:
  workflow_dispatch:
    inputs:
      app:
        type: choice
        description: Application
        options:
          - web
          - api

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Output image name
        id: image-name
        env:
          APP: ${{ github.event.inputs.app }}
        run: echo "IMAGE_NAME=ghcr.io/tithanayut/aomsin/$APP" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: apps/${{ github.event.inputs.app }}/Dockerfile
          push: true
          tags: ${{ steps.image-name.outputs.IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ steps.image-name.outputs.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ steps.image-name.outputs.IMAGE_NAME }}:buildcache,mode=max
